import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preload"
          href="https://use.typekit.net/tav0gkp.css"
          as="style"
        />
        <link rel="stylesheet" href="https://use.typekit.net/tav0gkp.css" />
      </head>
      <body>{children}</body>
    </html>
  );
}
